# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app-deployment
  namespace: trend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-app
  template:
    metadata:
      labels:
        app: trend-app
    spec:
      containers:
        - name: trend-app
          image: parthiban46/trend-app:latest
          ports:
            - containerPort: 80

